# Generated by Django 6.0.7 on 2026-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
