# Generated by Django 6.0.7 on 2026-07-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
